version: "3.9"  # optional since v1.27.0
services:
  api:
    build:
      context: ./src/FaunaAspNet.API
      dockerfile: ./Dockerfile
    ports:
      - "8000:80"
    environment:
      - Fauna:Secret=<SERVER_KEY>

